[Feature] weewx interceptor
felddy/weewx-docker pull request #21
Opened 2020-09-26 22:19 UTC by MarcHagen

# 

## 🗣 Description

Added [WeeWX-Interceptor](https://github.com/matthewwall/weewx-interceptor), this module allows you to intercept/receive data from a network weather station.

I have NOT added the sniff part (so the use of pypcap and such) as this is kinda complicated to do with Docker as it also requires a DNS/DHCP server.
Personally i find this out of the scope for the docker image, hench why i didn't add that dependency.

## 💭 Motivation and Context

It allows me to get data from my weather station and publish it over MQTT.

## 🧪 Testing

## 📷 Screenshots (if appropriate)

## 🚥 Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2020-10-12 16:37 UTC, felddy requested changes
Looks great!  Strong work!  💪 
Please see my one request for a change.

2020-10-12 16:37 UTC, felddy commented on README.md
> +* [interceptor](https://github.com/matthewwall/weewx-interceptor)
Just need to sort this list: 

```suggestion
* [interceptor](https://github.com/matthewwall/weewx-interceptor)
* [mqtt](https://github.com/weewx/weewx/wiki/mqtt)
```

2020-10-12 18:02 UTC, MarcHagen commented on README.md
> +* [interceptor](https://github.com/matthewwall/weewx-interceptor)
Updated branch with requested change.

2020-10-12 18:05 UTC, felddy approved these changes
Nice!  Thank you for the contribution!

2020-10-12 18:06 UTC, merged

2020-10-12 19:02 UTC, felddy commented
@MarcHagen ... just a heads up... the release workflow is having issues building the image and publishing it.  This isn't caused by any changes in this PR, but will delay `4.1.1+a` from get published.   I'm trying to debug it now.

2020-10-13 21:13 UTC, felddy commented
I was able to determine the root cause of the build errors.
See: #25

I've worked around this issue until it can be fixed upstream.  CI is now building the new `4.1.1` release and it should be pushed momentarily.    

Thank you again for your contribution!  💪